#!/bin/bash
echo "Welcome to your AI-Enhanced Shell Environment!"
echo "- Ubuntu 24.04 LTS"
echo "- tmux available (type: tmux)"
echo "- atuin shell history enabled"
echo "- Type Ctrl-R or 'atuin search' to search command history"
echo "- tmux prefix remapped to Ctrl-A"
echo ""
echo "🤖 AI Integration Features:"
echo "- Run 'ai-setup' to configure AI providers (OpenAI, Anthropic, Google, Ollama)"
echo "- Use @ prefix for AI queries: @how do I find large files"
echo "- Commands: ai, ai-last, ai-fix, ai-here, ai-context, ai-copy"
echo "- tmux AI keybindings:"
echo "  * Ctrl-A + A: Toggle AI input pane"
echo "  * Ctrl-A + I: Quick AI query"
echo "  * Ctrl-A + C: AI response manager"
echo "  * Ctrl-A + T: Test AI providers"
echo "" 