#!/bin/bash
echo "Welcome to your AI-Enhanced Shell Environment!"
echo ""
echo "🚀 Shell AI Go Implementation (Primary)"
echo "- Run 'shell-ai interactive' for conversational AI sessions"
echo "- Run 'shell-ai ask \"your question\"' for one-shot queries"
echo "- Run 'shell-ai setup' to configure AI providers"
echo "- Run 'shell-ai test' to test provider connections"
echo ""
echo "💡 Quick Start:"
echo "  shell-ai interactive    # Start interactive session"
echo "  ai \"your question\"      # Using alias"
echo "  @your question          # @ prefix still works"
echo ""
echo "🔧 Environment:"
echo "- Ubuntu 24.04 LTS"
echo "- tmux available (type: tmux)"
echo "- atuin shell history enabled"
echo "- Type Ctrl-R or 'atuin search' to search command history"
echo "- tmux prefix remapped to Ctrl-A"
echo ""
echo "⌨️  tmux AI Keybindings (Ctrl-A prefix):"
echo "  * Ctrl-A + S: Start interactive AI session"
echo "  * Ctrl-A + I: Quick AI query with prompt"
echo "  * Ctrl-A + Q: One-shot AI query"
echo "  * Ctrl-A + T: Test AI providers"
echo "  * Ctrl-A + E: Explain current pane output"
echo ""
echo "⚠️  Legacy Bash Implementation:"
echo "The bash scripts are deprecated. Use 'shell-ai' commands instead."
echo "" 